# Dependencies
markdown:            kramdown
highlighter:         rouge
plugins:             [jekyll-paginate]

# Permalinks
permalink:           pretty

# Setup
title:               4ier's Blog
description:         '爱与自由'
baseurl:             /git-blog

author:
  name:              4ier
  email:             yang.fourier@gmail.com

paginate:            5

# Custom vars
version:             2.0.0

github:
  repo:              https://github.com/4ier/

twitter:             https://twitter.com/yangfourier

excerpt_separator:  '<!-- more -->'